---
abstract: "Structure class for 'Tags' output."
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tags-Output-Structure
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.22
  Tags::Output: 0.03
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tags-Output-Structure
  homepage: https://github.com/tupinek/Tags-Output-Structure
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Tags-Output-Structure
version: '0.05'
